version: "3.7"

services:
  api:
    container_name: api
    build:
      context: ./api
      dockerfile: ./docker/Dockerfile.dev
    volumes:
      - ./api:/node
      # ":/tracks" should match the MUSIC_LIB_DIR env var in .common.env
      - /mnt/CE64EB6A64EB53AD/music-lib/tracks:/tracks
    expose:
      - "8080"
    ports:
      - "8080:8080"
      - "9229:9229"
    env_file:
      - ./api/docker/.test.env
      - ./postgres/docker/.test.env
      - ./.common.env
    depends_on:
      - testdb_postgres

  testdb_postgres:
    container_name: postgres
    build:
      context: ./postgres
      dockerfile: ./docker/Dockerfile.dev
    restart: always
    env_file:
      - ./postgres/docker/.dev.env
    ports:
      - 5433:5432
    volumes:
      - ./postgres/volume/:/var/lib/postgresql/data

  client:
    container_name: client
    build:
      context: ./client
      dockerfile: ./docker/Dockerfile.dev
    restart: "always"
    env_file:
      - ./.common.env
      - ./client/docker/.dev.env
    expose:
      - 3000
    ports:
      - "3000:3000"
    volumes:
      - ./client/:/client/

networks:
  frontnet:
    driver: bridge
