version: "3.7"

services:
  node:
    container_name: node
    build:
      context: ./node
      dockerfile: Dockerfile.dev
    volumes:
      - ./node/src:/node/src
      - ./node/tsconfig.json:/node/tsconfig.json
      - /mnt/CE64EB6A64EB53AD/music-lib/tracks:/tracks
    expose:
      - "8080"
    ports:
      - "8080:8080"
      - "9229:9229"
    env_file:
      - ./node/.env
      # Share Mongo's env vars like username, password, etc., with Node to be
      # able to connect to Mongo from Node container)
      - ./mongodb/.env

  postgres:
    container_name: postgres
    build:
      context: ./postgres
      dockerfile: Dockerfile
    restart: always
    env_file:
      - ./postgres/.env
    ports:
      - 5433:5432
    volumes:
      - ./postgres/volume/:/var/lib/postgresql/data
